# Generated by Django 5.2 on 2026-02-18 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0003_position_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='date_time',
            field=models.DateTimeField(),
        ),
    ]
