# Generated by Django 5.2 on 2026-03-01 19:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('positions', '0005_position_distance_position_speed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='position',
            options={'ordering': ['date_time']},
        ),
        migrations.AlterField(
            model_name='position',
            name='distance',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Накопленное расстояние в км от начала забега до этой точки', max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='position',
            name='latitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='longitude',
            field=models.DecimalField(decimal_places=6, max_digits=9),
        ),
        migrations.AlterField(
            model_name='position',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Скорость м/с между предыдущей и текущей позицией', max_digits=6, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
