# Generated by Django 5.2 on 2026-02-15 19:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artifacts', '0002_alter_collectibleitem_uid'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collectibleitem',
            name='user',
            field=models.ManyToManyField(related_name='collectible_items', to=settings.AUTH_USER_MODEL),
        ),
    ]
