# Generated by Django 5.2 on 2025-09-25 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='stutus',
            field=models.CharField(choices=[('init', 'Init'), ('in_progress', 'Progress'), ('finished', 'Finished')], default='init', max_length=15),
        ),
    ]
