# Generated by Django 5.2 on 2025-09-26 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0003_alter_run_stutus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='run',
            old_name='stutus',
            new_name='status',
        ),
    ]
