# Generated by Django 5.2 on 2026-02-04 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0005_athleteinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='athleteinfo',
            old_name='user_id',
            new_name='user',
        ),
    ]
