# Generated by Django 5.2 on 2026-02-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0006_rename_user_id_athleteinfo_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='athleteinfo',
            name='goals',
            field=models.TextField(blank=True, null=True),
        ),
    ]
