# Generated by Django 5.2 on 2026-02-10 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0010_run_distance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Challenge',
        ),
    ]
