# Generated by Django 5.2 on 2026-02-18 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0011_delete_challenge'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='run_time_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
