# Generated by Django 5.2 on 2026-03-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_run', '0013_alter_run_athlete'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='speed',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Средняя скорость за забег в м/с', max_digits=6),
        ),
    ]
